### ISSUE TITLE
unhandled Promise rejections

### ISSUE THREAD

**Issue by 958smsm** [planetlabs/planet-client-js#69]
(node:15928) UnhandledPromiseRejectionWarning: Error: status 502
    at responseError (D:\Osama Adly\vision\GIS\client\test\api\retry.test.js:27:15)
    at Context.<anonymous> (D:\Osama Adly\vision\GIS\client\test\api\retry.test.js:102:22)
    at callFnAsync (D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runnable.js:386:21)
    at Test.Runnable.run (D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runnable.js:330:7)
    at Runner.runTest (D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runner.js:621:10)
    at D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runner.js:745:12
    at next (D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runner.js:538:14)
    at D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runner.js:548:7
    at next (D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runner.js:430:14)
    at Immediate.<anonymous> (D:\Osama Adly\vision\GIS\client\node_modules\mocha\lib\runner.js:516:5)
    at processImmediate (internal/timers.js:439:21)
(node:15928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)

**Comment by tschaub** [comment]
It looks like you were running the tests when you got this.  I don't see the same currently.  Please reopen with additional information if this is still an issue.
